name: phoenix_wings
description: Phoenix Channel client for Dart
version: 1.0.2
author: mfeckie<mfeckie@gmail.com>
homepage: https://github.com/mfeckie/phoenix_wings

dev_dependencies:
  test: ^1.17.5
  mockito: ^5.0.9
  stream_channel: ^2.1.0
  intl: ^0.17.0
  build_runner: ^2.0.4

environment:
  sdk: ">=2.12.0 <3.0.0"
